AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

# frozen string literals is on by default from Ruby 3.4
Style/FrozenStringLiteralComment:
  Enabled: false