port: 12111
core_version: '3.1.2'
sxl: tlc
sxl_version: '1.0.7'
intervals:
  timer: 1
  watchdog: 60
timeouts:
  watchdog: 120
  acknowledgement: 20
  connect: 120
  ready: 60
  status_response: 60
  status_update: 60
  subscribe: 60
  command: 180
  command_response: 180
  alarm: 60
  disconnect: 120
  startup_sequence: 60
  functional_position: 30
  yellow_flash: 60
components:
  main:
    KK+AG9998=001TC000:
      ntsOId: KK+AG9998=001TC000
  signal_group:
    KK+AG9998=001SG001:
  detector_logic:
    KK+AG9998=001DL001:
items:
  plans: [3,4]
  traffic_situations: [1,2]
  emergency_routes: [1]
  inputs: [1,101]
  outputs: [1,2]
startup_sequence: 'efg'
secrets:
  security_codes:
    1: 2503
    2: 2503
