port: 13111
secure:
  required: true
  profile: rsmp-secure-v1
  log_decrypted_payloads: true
sites:
  default:
    sxls:
      tlc: '1.2.1'
    intervals:
      timer: 0.1
      watchdog: 0.1
    timeouts:
      watchdog: 0.5
      acknowledgement: 0.5
  RN+SI0001:
    sxls:
      tlc: '1.2.1'
