port: 13111
sites:
  default:
    sxl: tlc
    intervals:
      timer: 0.1
      watchdog: 0.1
    timeouts:
      watchdog: 0.5
      acknowledgement: 0.5
log:
  prefix: '[SUPERVISOR]'
  color:
    warning: 'magenta'
    info: 'light_cyan'
    log: 'cyan'
    debug: 'light_cyan'
  id: true
  port: true
  json: true
  acknowledgements: false
  watchdogs: false

