#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require_relative '../lib/rsmp/validator/compliance/collector'

options = {
  repo: ENV.fetch('COMPLIANCE_SOURCE_REPO', 'rsmp-nordic/rsmp_validator'),
  website_dir: 'rsmp_website',
  data_dir: 'rsmp_website_compliance_data',
  lookback_days: RSMP::Validator::Compliance::Collector::DEFAULT_LOOKBACK_DAYS,
  overlap_days: RSMP::Validator::Compliance::Collector::DEFAULT_OVERLAP_DAYS,
  full: false
}

OptionParser.new do |parser|
  parser.banner = 'Usage: compliance-collector [options]'

  parser.on('--repo REPO', 'GitHub repository to read workflow artifacts from') do |repo|
    options[:repo] = repo
  end

  parser.on('--website-dir PATH', 'Checked out website main branch directory') do |path|
    options[:website_dir] = path
  end

  parser.on('--data-dir PATH', 'Checked out website compliance-data branch directory') do |path|
    options[:data_dir] = path
  end

  parser.on('--lookback-days DAYS', Integer, 'How many days of runs to inspect in full mode') do |days|
    options[:lookback_days] = days
  end

  parser.on('--overlap-days DAYS', Integer, 'How many previous days to reprocess in incremental mode') do |days|
    options[:overlap_days] = days
  end

  parser.on('--full', 'Ignore existing compliance-data summary and rebuild from the lookback window') do
    options[:full] = true
  end
end.parse!

token = ENV['GH_TOKEN'] || ENV.fetch('GITHUB_TOKEN', nil)
abort 'GH_TOKEN or GITHUB_TOKEN is required' unless token && token != ''

github = RSMP::Validator::Compliance::GitHubClient.new(repo: options[:repo], token: token)

RSMP::Validator::Compliance::Collector.new(
  github: github,
  website_dir: options[:website_dir],
  data_dir: options[:data_dir],
  source_repo: options[:repo],
  lookback_days: options[:lookback_days],
  overlap_days: options[:overlap_days],
  full: options[:full]
).collect
