#!/usr/bin/env ruby

require 'bundler/setup'
require 'sus'
require 'sus/config'

# Parse --log [path] from ARGV before Sus::Config.load consumes remaining args.
# --log        => RSMP logs to $stdout
# --log <path> => RSMP logs to file, sus output to console (brief)
# (no --log)   => RSMP logs suppressed
log_index = ARGV.index('--log')
log_path = nil
log_to_stdout = false
if log_index
  ARGV.delete_at(log_index)
  if ARGV[log_index] && !ARGV[log_index].start_with?('-')
    log_path = ARGV.delete_at(log_index)
  else
    log_to_stdout = true
  end
end

# Load config/validator.rb instead of config/sus.rb so that conformance tests
# live in valid/site/ and valid/supervisor/, keeping them separate from the
# internal tests in test/ that plain `sus` runs.
validator_config_class = Class.new(Sus::Config) do
  attr_accessor :log_to_stdout, :log_path

  def self.path(root)
    path = ::File.join(root, 'config/validator.rb')
    ::File.exist?(path) ? path : nil
  end
end

config = validator_config_class.load
config.log_to_stdout = log_to_stdout
config.log_path = log_path

registry = config.registry

output = config.verbose? ? config.output : Sus::Output::Null.new
verbose = config.verbose?

assertions = Sus::Assertions.default(output: output, verbose: verbose)

config.before_tests(assertions)
registry.call(assertions)
config.after_tests(assertions)

exit(1) unless assertions.passed?
