source 'https://rubygems.org'

gem 'jekyll', '~> 4.4'
gem 'jekyll-include-cache'
gem 'just-the-docs'   # Jekyll theme
gem 'sass-embedded', '< 1.84'  # to support older Mac OS 13
gem 'wdm', platforms: %i[mingw x64_mingw mswin] # Performance-booster for watching directories on Windows

gem 'base64'
gem 'bigdecimal'
gem 'csv'
gem 'logger'

group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-remote-theme'
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem 'tzinfo'
  gem 'tzinfo-data'
end


