# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will run rspec

name: Swarco ITC-3
on:
  pull_request:
    types: [ opened, reopened, synchronize, labeled ]
  schedule:
    # schedule runs only on the default branch. time is in UTC.
    # * is a special character in YAML so you have to quote this string.
    # run every night at 10:00PM UTC.
    - cron:  '0 22 * * *'
jobs:
  validator:
    if: ${{ github.event_name == 'schedule' || contains(github.event.pull_request.labels.*.name, 'testhub') }}
    runs-on: [ self-hosted, Linux, X64, itc3 ]
    strategy:
      matrix:
        core: ['3.2.0', '3.1.5', '3.1.4', '3.1.3', '3.1.2']
      fail-fast: false

    steps:
    - name: Set log id
      shell: bash
      id: log_id
      run: |
        echo "LOG_ID=\
        swarco-itc3-\
        core-${{ matrix.core }}-\
        run-\
        ${{ github.run_id }}-\
        ${{ github.run_number }}-\
        ${{ github.run_attempt }}\
        " >> $GITHUB_OUTPUT

    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Ruby and gems
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run tests
      run: |
        bundle exec rspec spec/site \
        --format Validator::Brief \
        --format Validator::Details \
        --out validator-${{ steps.log_id.outputs.LOG_ID }}.log
      env:
        SITE_CONFIG: config/swarco_itc3.yaml
        CORE_VERSION: ${{ matrix.core}}

    - name: Show detailed log
      shell: bash
      if: always() # even if previous steps failed
      run: cat validator-${{ steps.log_id.outputs.LOG_ID }}.log
    
    - name: Upload validator.log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: validator-${{ steps.log_id.outputs.LOG_ID }}.log
        path: validator-${{ steps.log_id.outputs.LOG_ID }}.log
